layers: [512, 128]
buffer_size: 10000
learning_rate: !!float 1e-4
learning_starts: 10000
target_network_update_freq: 1000
train_freq: 4
exploration_final_eps: 0.01
exploration_fraction: 0.1
prioritized_replay_alpha: 0.6
cnn: True
ln: False
dueling: True